stages:
  process_data: # Process data
    cmd: python code/ml_training/process_data.py
    deps:
    - data/raw/groceries.csv
    - code/ml_training/process_data.py
    outs:
    - data/prepared/prepared.csv
  
  train: # Train processed data
    cmd: python code/ml_training/train.py
    deps:
    - data/prepared/prepared.csv
    - code/ml_training/train.py
    outs:
    - model/association_rules.pkl