name: Build recommendation app

on:
    push:
        branches: ["master"]

jobs:
    docker:
        runs-on: ubuntu-latest
        env:
            DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}

        steps:
            - uses: actions/checkout@v2

            - name: docker login
              env:
                DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
                DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

              run: |
                docker login -u $DOCKERHUB_USER -p $DOCKERHUB_ACCESS_TOKEN

            - name: docker build
              run: | # Tag the image with the commit hash
                docker build -t $DOCKERHUB_REPOSITORY .
                docker tag $DOCKERHUB_REPOSITORY:latest $DOCKERHUB_REPOSITORY:$(git log -1 --pretty=%h)

            - name: docker push
              run: |
                docker push $DOCKERHUB_REPOSITORY