name: Build recommendation app

on:
    push:
        branches: ["master"]
        paths:
          - src/**
          - data/*
          - .github/workflows/*
          - .dvc/*
          - Dockerfile

env:
    DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}

jobs:
    docker:
        name: App build & deploy pipeline
        runs-on: ubuntu-latest
          
        steps:
          - uses: actions/checkout@v2

          - name: Pull model from DVC
            run: |
              pip install dvc dvc-gdrive
              dvc get https://dagshub.com/ericdasse28/market-basket-analysis model/association_rules.pkl
              mv association_rules.pkl model/

          - name: docker login
            env:
              DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
              DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            run: |
              docker login -u $DOCKERHUB_USER -p $DOCKERHUB_ACCESS_TOKEN

          - name: docker app build
            run: | # Tag the image with the commit hash
              docker build -t $DOCKERHUB_REPOSITORY:${GITHUB_SHA::6} .

          - name: docker app deploy
            run: |
              docker push $DOCKERHUB_REPOSITORY:${GITHUB_SHA::6}

          - name: docker app release
            run: |
              docker pull $DOCKERHUB_REPOSITORY:${GITHUB_SHA::6}
              docker tag $DOCKERHUB_REPOSITORY:${GITHUB_SHA::6} $DOCKERHUB_REPOSITORY:latest
              docker push $DOCKERHUB_REPOSITORY:latest
