name: ML pipeline

on:
    push:
        branches: [ "master" ]
        paths:
            - code/ml_training/**
            - data/*
            - .github/workflows/*
            - .dvc/*

jobs:
    run_code:
        name: Model build pipeline
        runs-on: ubuntu-latest
        steps:
            - name: Check out the current repository
              id: checkout
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                python -m pip install -U pip
                python -m pip install -r requirements.txt

            - name: Pull data from DVC
              run: |
                dvc remote modify origin --local auth basic
                dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
                dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}
                dvc pull

            - name: Run the pipeline with DVC
              run: dvc repro

            - name: Push the outcomes to DVC remote storage
              run: dvc push

            - name: Commit changes in dvc.lock
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: Commit changes in dvc.lock
                branch: master
                file_pattern: dvc.lock
