name: Run ML pipeline
on:
    push:
        branches:
            - master
        paths:
            - src/**
            - data/*

jobs:
    run_code:
        name: Run code
        runs-on: ubuntu-latest
        container: ericdasse28/groceries_association_rules:dvc
        steps:
            - name: Check out the current repository
              id: checkout
              uses: actions/checkout@v2

            - name: Pull data from DVC
              run: |
                dvc remote modify origin --local auth basic
                dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
                dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}
                dvc pull

            - name: Run the pipeline with DVC
              run: dvc repro

            - name: Push the outcomes to DVC remote storage
              run: dvc push

            - name: Commit changes in dvc.lock
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: Commit changes in dvc.lock
                branch: master
                file_pattern: dvc.lock
